# Generated by Django 4.1.3 on 2022-11-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0002_alter_supers_super_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='super_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_types.super_types'),
            preserve_default=False,
        ),
    ]
